import { useMemo } from "react";
import { assetUrl } from "../lib/api-base";
import { MediaImage } from "./MediaImage";

type Props = {
  /** Server-generated SVG markup (preferred — never depends on Cloudinary). */
  qrSvg?: string | null;
  /** Cloudinary / data / absolute PNG URL (fallback). */
  qrCodeUrl?: string | null;
  alt: string;
  className?: string;
  background?: string;
  cacheKey?: string | number;
};

/**
 * Always-visible QR preview.
 * Prefers inline SVG from the API so the portal works even when Cloudinary
 * delivery fails or a data-URL was cache-busted incorrectly.
 */
export function QrCodeImage({
  qrSvg,
  qrCodeUrl,
  alt,
  className = "",
  background = "#FFFFFF",
  cacheKey,
}: Props) {
  const svgMarkup = useMemo(() => {
    const raw = qrSvg?.trim();
    if (!raw) return null;
    // Only accept SVG we generated server-side.
    if (!/^<svg[\s>]/i.test(raw)) return null;
    return raw;
  }, [qrSvg]);

  const pngSrc = useMemo(() => {
    const resolved = assetUrl(qrCodeUrl);
    if (!resolved) return null;
    if (
      resolved.startsWith("data:") ||
      resolved.startsWith("blob:") ||
      cacheKey === undefined ||
      cacheKey === null ||
      cacheKey === ""
    ) {
      return resolved;
    }
    const sep = resolved.includes("?") ? "&" : "?";
    return `${resolved}${sep}v=${encodeURIComponent(String(cacheKey))}`;
  }, [qrCodeUrl, cacheKey]);

  if (svgMarkup) {
    return (
      <div
        className={["overflow-hidden [&_svg]:h-full [&_svg]:w-full", className].join(
          " ",
        )}
        style={{ background }}
        role="img"
        aria-label={alt}
        // Trusted: SVG is generated by our server with qrcode, not user HTML.
        dangerouslySetInnerHTML={{ __html: svgMarkup }}
      />
    );
  }

  if (pngSrc) {
    return (
      <MediaImage
        src={pngSrc}
        alt={alt}
        className={className}
      />
    );
  }

  return (
    <div
      className={[
        "flex items-center justify-center bg-black/25 text-xs text-[var(--muted)]",
        className,
      ].join(" ")}
      role="img"
      aria-label={alt}
    >
      No image
    </div>
  );
}
